target "mqrc" do


    pod 'SDCycleScrollView'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'IQKeyboardManager'
    pod 'IQDropDownTextField'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'SDWebImage', '~>3.8'
    pod 'TZImagePickerController'
    pod 'MJRefresh'
    pod 'WMPageController'
    pod 'FDFullscreenPopGesture', '~> 1.1'
    pod 'KMNavigationBarTransition'
    pod 'DZNEmptyDataSet'
    pod 'MJExtension'
    pod 'pop', '~> 1.0'
    pod 'YZTagList'
    pod 'PGDatePicker', '>= 1.5.9'
    pod 'TXScrollLabelView'
    pod 'CYLTabBarController', '~> 1.17.4'
    pod 'JPush'
    pod 'NSHash', '~> 1.2.0'
    #第三方SDK#
    pod 'AMapLocation'
    pod 'AMap3DMap'
    pod 'AMapSearch'
    
end
